model:
  base_learning_rate: 4.5e-6
  target: Taming.models.vqvae.VQVAE
  params:
    embed_dim: 256
    n_embed: 1024
    codebook_weight: 1
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: Taming.data.custom.CustomTrain
      params:
        training_images_list_file: some/training.txt
        size: 32
    validation:
      target: Taming.data.custom.CustomTest
      params:
        test_images_list_file: some/test.txt
        size: 32
